services:
  - type: web
    name: code-storage-api
    env: node
    region: singapore
    plan: free
    buildCommand: pnpm install && BASE_PATH=/ pnpm --filter @workspace/code-storage run build && pnpm --filter @workspace/api-server run build
    startCommand: pnpm --filter @workspace/api-server run start
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
